### ISSUE TITLE
16-bit depth extractor 

### ISSUE THREAD

**Issue by RapIt** [NVIDIA/Dataset_Synthesizer#10]
Hi, 
related to another [issue](https://github.com/NVlabs/Deep_Object_Pose/issues/45) (last comments) in the DOPE repo, I fail to make any of the 16bit depth extractors work. 
On the following image (left) the 8-bit map (middle) works fine, whereas the 16-bit map (right) appears to be too flat:
![all](https://user-images.githubusercontent.com/844913/62879950-8939fb80-bd2c-11e9-8b72-e9376b6acc68.png)

Minimum and Maximum values of the depth map are also strange on the 16-bit image:
min: 10502 max: 13311, so only a depth distance of 30cm and the minimum is too far away. 
 
I got the same results with all three SceneCaptures and with all depth extractors (quantized and absolute) I did a `depth_image * MAX_DEPTH / 2^16` conversation to get the real depth values. 

Am I misunderstanding something or is the extractor broken?
Working with the current version under linux.
Thanks!

**Comment by thangt** [comment]
@RapIt I fixed the problem with the 16bits depth feature extractors in the latest commits. Can you pull the latest commits and try this again? I also added 2 more absolute feature extractor: 16 bits cm depth and 8 bits cm depth. Using these, you don't need to do the conversion to get the real depth value, you can use the value directly.

**Comment by RapIt** [comment]
Thanks for the fix! Both Quantized_16bit and the new cm_16bit work perfectly fine now.
