### ISSUE TITLE
Instance Segmentation background color

### ISSUE THREAD

**Issue by plasma-vision** [NVIDIA/Dataset_Synthesizer#14]
I've been trying to figure out how the color for the background is chosen in the rendering of the Instance Segmentation output, but I find myself going in circles. I can see how they are chosen for the actors based on the MaskID, but I have been unable to find where the color for the background is specified. Any info you could provide would be much appreciated.

**Comment by thangt** [comment]
The Instance Segmentation gave all the objects in the scene a mask id which include those distractors or background objects. You can keep a list of the annotated objects that you care about and ignore all the other object mask.
Do you need to control the color of the background or you just want to understand how things work?

**Comment by plasma-vision** [comment]
I thought it might be something like that. 
I'm just trying to understand how it works. 
I figured out that I can map the instance_id to the mask color using the algorithm ConvertInt32ToVertexColor defined in NVSceneCaptureUtils.cpp. 
I assume that is a good way to figure out which particular color of mask refers to a specific object instance. If that is so, I don't need to worry about the background color.
Many thanks for your help.

**Comment by thangt** [comment]
Yes, that function is the one we use to convert the id to the color on the segmented image.
As I mentioned before, most of the time you only need to care about the annotated objects, all the other can just be considered as noises and be ignored when you do training.

**Comment by smitheric95** [comment]
Hey @thangt, I know this is a very old thread, but I'd like the instance masks to have a background value of `0` and flying distractors to not be visible in the `.is.png` images. 

Do you know how I can achieve this?
