### ISSUE TITLE
Captured image sizes with width > 1024

### ISSUE THREAD

**Issue by plasma-vision** [NVIDIA/Dataset_Synthesizer#15]
I don't expect anyone to troubleshoot this on my behalf because it's an unusual use-case. I'm just reporting it for reference.
If you try to set the Image Capture Size to anything with a width exceeding 1024, it the output images look like an old TV that has lost sync. 
I was trying to create a capturer that matched the intrinsics and output of a camera I am using when I ran into the problem. 
I will dig into it, and if I find anything useful, I will report back.

**Comment by mikeramseybg** [comment]
Interesting you’re seeing this, I’ve been generating targets that are 1920x1200 with no unexpected distortion. Here are my camera settings that work (they to are derived from a real-world camera…):
    resolutionX         = 1920   #resolution of camera target image
    resolutionY         = 1200
    focalX              = 2747   # focal length
    focalY              = 2747
    principal_pointX    = 881   # principal point
    principal_pointY    = 614
    skew                = 0.0   # skew coefficient
    fov_min             = 90    # field of view range
    fov_max             = 90


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by plasma-vision** [comment]
Good to know. Your settings aren't too different from mine. Must be an artifact of something within my system, or the result of some change I've made. I'll try with a fresh setup and see what happens. Thanks for the feedback.

**Comment by plasma-vision** [comment]
You are correct. A freshly downloaded setup handles it just fine.
