### ISSUE TITLE
TestCapturer not working in 4.22

### ISSUE THREAD

**Issue by marckernest** [NVIDIA/Dataset_Synthesizer#17]
Hey folks, so I had been using 4.21, which works well. I wanted to migrate to 4.22 to use ray tracing.  That's when I started to encounter problems. So, I recently started from scratch in 4.22, and for whatever reason, the "testscapturer" cannot capture any data. Please help!

**Comment by marckernest** [comment]
I follow each step in the documentation and I cannot get it to work properly.

**Comment by thangt** [comment]
Are you running the latest NDDS right now?
Did you make any change to the TestCapturer map?

**Comment by marckernest** [comment]
![10 09 2019 11 11](https://user-images.githubusercontent.com/53339941/64601385-21bfac00-d3bd-11e9-9c8a-6e3d01a128f4.PNG)
> Are you running the latest NDDS right now?
> Did you make any change to the TestCapturer map?

Yes, and no. Here's a screenshot. I managed to "import" the parent class BP for the testcapturer, but not the testcapturer itself. Even then, I don't know why I have to import anything at all especially if I start from scratch...

**Comment by thangt** [comment]
I think I understand your problem now. You created a new map and bring the SceneCapture_Simple over to capture it.
Did you also added a SceneManager_BP to your new map? You need it to actually drive the capturing process. You can check the TestCapturer map to see how it's setup.

**Comment by thangt** [comment]
Seem to me the error with NVSceneCapturerGameHUD_BP is what cause the HUD to not appear. It look like that blueprint failed to migrate over.
Are you using a custom UE4 (engine with custom code)? Also which platform are you running this? 
Right now, I don't have clear idea what's happening yet since I can't reproduce the problem locally.
If we still can't figure out then I may need to zip up the project and let you try it.

**Comment by marckernest** [comment]
> Seem to me the error with NVSceneCapturerGameHUD_BP is what cause the HUD to not appear. It look like that blueprint failed to migrate over. **That was exactly the case. It's the case with all these problems. I had opened an issue about this before. Many BPs, if not all, failed to migrate.**
> Are you using a custom UE4 (engine with custom code)? Also which platform are you running this? **Windows 10 Pro for Workstations (1903). And I am not using any special version of UE4. It's just 4.22.3, maybe it is a problem with source control? I don't use it.**
> Right now, I don't have clear idea what's happening yet since I can't reproduce the problem locally.
> If we still can't figure out then I may need to zip up the project and let you try it.

After migrating all BPs, I don't seem to have any issues now. Just FYI to someone reading, be mindful of file structure if you're manually migrating BPs.
