### ISSUE TITLE
Incorrect bounding_box dimensions on data export. 

### ISSUE THREAD

**Issue by smitheric95** [NVIDIA/Dataset_Synthesizer#18]
I'm getting incorrect `bounding_box` dimensions on simple cube-like actors. I've reproduced this issue on UE 4.21 with NDDS v1.1 as well as UE 4.22 with the latest NDDS commit. 

Below is an example. Notice that the bounding box is very far off with respect to the location and cuboid. 

```
{
			"class": "cube2",
			"instance_id": 14,
			"segmentation_class_id": 5,
			"segmentation_instance_id": 14,
			"visibility": 0,
			"location": [ 112.7113037109375, 75.990898132324219, 225.98260498046875 ],
			"quaternion_xyzw": [ -0.71619999408721924, 0.69760000705718994, 0.0013000000035390258, -0.021600000560283661 ],
			"pose_transform": [
				[ -0.15369999408721924, -0.14000000059604645, -4.7954998016357422, 0 ],
				[ 0.10050000250339508, -3.7471001148223877, 0.10620000213384628, 0 ],
				[ 3.5968999862670898, 0.093199998140335083, -0.11800000071525574, 0 ],
				[ 112.7113037109375, 75.990898132324219, 225.98260498046875, 1 ]
			],
			"cuboid_centroid": [ 112.70860290527344, 76.033599853515625, 225.97419738769531 ],
			"projected_cuboid_centroid": [ 624.32220458984375, 444.7001953125 ],
			"bounding_box":
			{
				"top_left": [ -21585.841796875, -196730.453125 ],
				"bottom_right": [ 194923.109375, 1012.8798828125 ]
			},
			"cuboid": [
				[ 95.781303405761719, 56.772098541259766, 254.08050537109375 ],
				[ 94.0115966796875, 98.204399108886719, 250.59910583496094 ],
				[ 131.16709899902344, 99.687896728515625, 249.36790466308594 ],
				[ 132.93670654296875, 58.255599975585938, 252.84930419921875 ],
				[ 94.250099182128906, 52.379299163818359, 202.58059692382812 ],
				[ 92.480400085449219, 93.811599731445312, 199.09910583496094 ],
				[ 129.63589477539062, 95.295196533203125, 197.86790466308594 ],
				[ 131.40559387207031, 53.862899780273438, 201.34930419921875 ]
			],
			"projected_cuboid": [
				[ 549.10882568359375, 374.91390991210938 ],
				[ 547.98187255859375, 478.91018676757812 ],
				[ 641.1383056640625, 483.77789306640625 ],
				[ 640.98797607421875, 379.20819091796875 ],
				[ 603.622314453125, 396.59719848632812 ],
				[ 603.1572265625, 527.8726806640625 ],
				[ 720.9031982421875, 534.31207275390625 ],
				[ 719.3353271484375, 402.12249755859375 ]
			]
		}
```

Note, each actor is scaled using their Construction Script. This scale does not change and seems to be accurately reflected in the exported cuboid dimensions. 

![construction_script](https://user-images.githubusercontent.com/9437846/65079009-e1839f00-d963-11e9-9ddb-6b57d44ca2b9.png)

The collision boxes also seem to be accurate, which I know affects the calculated bounding box. 

![collision](https://user-images.githubusercontent.com/9437846/65079268-6078d780-d964-11e9-9d86-38bbfc8bbd5d.png)

There are nine different classes of cube in total that I'm generating using `Spatial Layout Generator Grid 2d`.

![cubes](https://user-images.githubusercontent.com/9437846/65079524-ff053880-d964-11e9-95c2-06de4db88dfa.png)

**Comment by thangt** [comment]
I can't repro this problem in my machine. Does this problem also happen if you just set the scale of the StaticMeshComponent (the box) of the actor manually?

**Comment by smitheric95** [comment]
Yes it does.

**Comment by thangt** [comment]
Hmm.
https://github.com/NVIDIA/Dataset_Synthesizer/commit/71b759e394a4a73f680b3371b82b7981102f6b3c => I did this commit to fix the problem with the annotated actor using scale. I shouldn't cause problem anymore.
If you can send me the blueprint and the map file I try to repro this issue on my machine.

**Comment by smitheric95** [comment]
I was able to resolve the problem! One of my static mesh components must have been corrupted. 

The mesh was based off an SVG file. I simply re-created the mesh in blender and re-exported it to Unreal, and now everything seems to be working correctly. 

I am still confused as to the discrepancy between the cuboid dimensions and the bounding box, however, I will mark the issue as resolved.
