### ISSUE TITLE
why there are no plugins in the content browser?

### ISSUE THREAD

**Issue by qingchenkanlu** [NVIDIA/Dataset_Synthesizer#19]
![QQ图片20190918214527](https://user-images.githubusercontent.com/44363924/65154496-33105480-da5e-11e9-8ca7-a520a1b04f6f.png)

**Comment by smitheric95** [comment]
Have you tried clicking `View Options > Show Plugin Content`? 

![Screenshot from 2019-09-18 10-48-52](https://user-images.githubusercontent.com/9437846/65164148-f31b8400-da01-11e9-8f1e-35f22e9f4101.png)

**Comment by qingchenkanlu** [comment]
thanks!
