### ISSUE TITLE
How do you bring in a level instead of a random background?

### ISSUE THREAD

**Issue by wightwhale** [NVIDIA/Dataset_Synthesizer#21]
I've added another level to the demo but it's unloaded when I hit play. Is there a way to keep the level I've added? I'm trying to replicate the realistic image production instead of the random background and I'm unsure how to proceed.

**Comment by thangt** [comment]
What do you mean by `added another level to the demo`? Did you add a new sub-level to the default map? You may need to change the streaming method of your sublevel to `Always Loaded`: https://docs.unrealengine.com/en-US/Engine/Levels/CollaborateWithSublevels/index.html.

**Comment by wightwhale** [comment]
Thanks that worked.
