### ISSUE TITLE
Remove "SM_RailRig_Mount" from .json

### ISSUE THREAD

**Issue by tancredosouza** [NVIDIA/Dataset_Synthesizer#23]
Hi!
How can I prevent this class "SMRailrig_Mount" from being tracked? I have no idea what this is...

 This is a part of the output generated by my SceneCapturer.

Thank you. 

`{
	"camera_data":
	{
		"location_worldframe": [ -720, 10, 150 ],
		"quaternion_xyzw_worldframe": [ 0, 0, 0, 1 ]
	},
	"objects": [
		{
			"class": "SM_RailRig_Mount",
			"instance_id": 16268800,
			"visibility": 1,
			"location": [ -203.99249267578125, -199.49519348144531, 182.39869689941406 
         ],
         ...
}
`

**Comment by thangt** [comment]
That SM_RailRig_Mount is 1 of the example object in the default map. It look like this:
![image](https://user-images.githubusercontent.com/8795674/66334067-278dac00-e8ed-11e9-97a6-9ede7300bf96.png)

**Comment by tancredosouza** [comment]
Thank you!
