### ISSUE TITLE
Importing YCB Objects

### ISSUE THREAD

**Issue by bjbraun** [NVIDIA/Dataset_Synthesizer#24]
Hey,

in which way did you import the YCB objects into Unreal Engine such that you can use the meshes to render the images?
On the YCB Website (http://ycb-benchmarks.s3-website-us-east-1.amazonaws.com/) it is possible to download the processed data or the laserscan. However, they do not provide a .fbx file for the unreal engine.

How did you create these .fbx files?

Thank you really much in advance!

Best regards,
Björn

**Comment by thangt** [comment]
UE4 does support .obj files, you don't need to convert it to .fbx files.
The official YCB is not aligned well, so when we generating the training data for DOPE or FAT dataset, we re-aligned them. You can use the NVDU tool: https://github.com/NVIDIA/Dataset_Utilities#nvdu_ycb to download and generate the aligned YCB models. You can drag those .obj files into UE4 afterward.

**Comment by bjbraun** [comment]
Thank you really much for your fast reply!
Is it also possible to download objects that are not in your list? Or how would you proceed with a object that is not in your list?
I specifically need the 012_strawberry object.

**Comment by zxprog** [comment]
> Thank you really much for your fast reply!
> Is it also possible to download objects that are not in your list? Or how would you proceed with a object that is not in your list?
> I specifically need the 012_strawberry object.

Excuse me,Could you teach me how to apply the NDDS plugins to UE4?

**Comment by bjoern-braun** [comment]
Just follow the instructions in the Documentation of this repository, that is all I did. Then the plugin should be available in UE4 :).

**Comment by thangt** [comment]
@bjbraun You can import any .obj 3d model into UE4. The objects in my list are just better aligned so it's easier to debug: root of the 3d model is at the cuboid center, object is stand up straight with the main label facing out. You can realign those object yourself (or not) and the training should still be ok.

**Comment by zxprog** [comment]
First , Thanks for your response. 
I have downloaded the NDDS,but i can not find it in the UE4 plugin meun.I guess that if I need to move the plugins floder of NDDS to the plugins floder of UE4 or just creat a new plugin and then replace the new plugin with the plugin of NDDS.The documentation include a folder named class_details and a pdf file named NDDS.However i just can not find the instructions about applying the plugins to UE4.May i find the wrong place?


Thank you very much!
 



------------------ 原始邮件 ------------------
发件人: "bjbraun"<notifications@github.com>; 
发送时间: 2019年10月15日(星期二) 晚上9:23
收件人: "NVIDIA/Dataset_Synthesizer"<Dataset_Synthesizer@noreply.github.com>; 
抄送: "死不忍错"<972229787@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [NVIDIA/Dataset_Synthesizer] Importing YCB Objects (#24)




Just follow the instructions in the Documentation of this repository, that is all I did. Then the plugin should be available in UE4 :).

**Comment by bjoern-braun** [comment]
@thangt Alright, thank you really much!

**Comment by bjoern-braun** [comment]
@zxprog Just follow this link and press download to get the documentation. There everything is explained in detail :)

https://github.com/NVIDIA/Dataset_Synthesizer/blob/master/Documentation/NDDS.pdf

**Comment by zxprog** [comment]
I am sorry to bother you so many times.
In fact, I have read this document many times.I may not express my meaning clearly.I know the function of this plugin.However, I don't know how to add these plugins into UE4 and the  document does not mention how to add third-party plugins to ue4.For example, I can find my plugin under the Edit/plugins bar.Currently I am creating a new plugin and then replacing it with  the downloaded plugin in the data_sys.I don't know if this is correct.





------------------ 原始邮件 ------------------
发件人: "bjbraun"<notifications@github.com>;
发送时间: 2019年10月16日(星期三) 下午3:51
收件人: "NVIDIA/Dataset_Synthesizer"<Dataset_Synthesizer@noreply.github.com>;
抄送: "死不忍错"<972229787@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [NVIDIA/Dataset_Synthesizer] Importing YCB Objects (#24)




@zxprog Just follow this link and press download to get the documentation. There everything is explained in detail :)
 
https://github.com/NVIDIA/Dataset_Synthesizer/blob/master/Documentation/NDDS.pdf

**Comment by bjoern-braun** [comment]
I am sorry but I do not know the solution to your problem. After I followed the download instructions, the NDDS plugin was listed in my project

**Comment by thangt** [comment]
@zxprog Are you trying to add the NDDS plugin into your own project? The current NDDS repo include the whole UE4 project setup include the plugin. If you place the NDDS plugins - mean all the plugins in this folder: https://github.com/NVIDIA/Dataset_Synthesizer/tree/master/Source/Plugins you should be able to have it work.

**Comment by TrinhNC** [comment]
I have a question. How do you add the texture to the object in unreal engine? For example, I input the .obj of the master_chef_can from [YCB](http://ycb-benchmarks.s3-website-us-east-1.amazonaws.com/) to UE and used the provided texture image to create the material but when I applied the material on the object, it just not showed up.

**Comment by zxprog** [comment]
Thanks for your response.Your words reminded me.Because I am using  version(ue4 4.21) and the project prompted that the project was created by a higher version.So I created a project myself and tried to find a way to add the plugins to ue4.I am preparing to download a newer version.Is your version 4.22?Thank you very much!




------------------ 原始邮件 ------------------
发件人: "Thang To"<notifications@github.com>; 
发送时间: 2019年10月17日(星期四) 凌晨1:47
收件人: "NVIDIA/Dataset_Synthesizer"<Dataset_Synthesizer@noreply.github.com>; 
抄送: "死不忍错"<972229787@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [NVIDIA/Dataset_Synthesizer] Importing YCB Objects (#24)




@zxprog Are you trying to add the NDDS plugin into your own project? The current NDDS repo include the whole UE4 project setup include the plugin. If you place the NDDS plugins - mean all the plugins in this folder: https://github.com/NVIDIA/Dataset_Synthesizer/tree/master/Source/Plugins you should be able to have it work.

**Comment by thangt** [comment]
@zxprog Yes, we are in 4.22. You can check our release page: https://github.com/NVIDIA/Dataset_Synthesizer/releases for the release notes.

@TrinhTUHH When you import the .obj into UE4 it should automatically import the model's texture and create a material for it too. Can you take a screenshot of how your imported object and material look like?

**Comment by zxprog** [comment]
I have installed version 4.22.3.But it cannot open.my visual studio vesion is 2015.Does this affect my project?

 



------------------ 原始邮件 ------------------
发件人: "Thang To"<notifications@github.com>; 
发送时间: 2019年10月18日(星期五) 凌晨1:27
收件人: "NVIDIA/Dataset_Synthesizer"<Dataset_Synthesizer@noreply.github.com>; 
抄送: "死不忍错"<972229787@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [NVIDIA/Dataset_Synthesizer] Importing YCB Objects (#24)




@zxprog Yes, we are in 4.22. You can check our release page: https://github.com/NVIDIA/Dataset_Synthesizer/releases for the release notes.
 
@TrinhTUHH When you import the .obj into UE4 it should automatically import the model's texture and create a material for it too. Can you take a screenshot of how your object look like?

**Comment by thangt** [comment]
@zxprog UE4 version 4.22 and later require VisualStudio version 2017 and newer. You should install VS2017 to work with this project. The free VS2017 community version should be good enough to build the project

**Comment by zxprog** [comment]
Thanks for your patience ! I will try it !




------------------ 原始邮件 ------------------
发件人: "Thang To"<notifications@github.com>; 
发送时间: 2019年10月19日(星期六) 凌晨1:38
收件人: "NVIDIA/Dataset_Synthesizer"<Dataset_Synthesizer@noreply.github.com>; 
抄送: "死不忍错"<972229787@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [NVIDIA/Dataset_Synthesizer] Importing YCB Objects (#24)




@zxprog UE4 version 4.22 and later require VisualStudio version 2017 and newer. You should install VS2017 to work with this project. The free VS2017 community version should be good enough to build the project

**Comment by DOPE-liyulong** [comment]
> UE4 确实支持 .obj 文件，您不需要将其转换为 .fbx 文件。 官方的YCB没有很好的对齐，所以当我们为DOPE或FAT数据集生成训练数据时，我们重新对齐了它们。您可以使用 NVDU 工具：[https](https://github.com/NVIDIA/Dataset_Utilities#nvdu_ycb) : [//github.com/NVIDIA/Dataset_Utilities#nvdu_ycb](https://github.com/NVIDIA/Dataset_Utilities#nvdu_ycb)下载并生成对齐的 YCB 模型。之后您可以将这些 .obj 文件拖入 UE4。
![image](https://user-images.githubusercontent.com/56593001/144033738-e5d5f265-7042-44d4-a6c8-faa59ba5290b.png)
AttributeError: 'NoneType' object has no attribute 'obj_settings'
I encountered this problem when using NVDU, could you please help me solve it

**Comment by mfheinemann** [comment]
@TrinhNC I am having the same issue, importing the original models from YCB either fails because "textured could not be created because all of its polygons are degenerate" or the import is successful but the mesh itself is empty. 

@thangt how do you align the model to work in UE4 ?
