### ISSUE TITLE
How can I rotate the camera (not random, but specific 360 degree loop) around a specific object? 

### ISSUE THREAD

**Issue by banannakn** [NVIDIA/Dataset_Synthesizer#25]
I try to create a dataset for my deep learning neural network. For this reason I need a bunch of photos of different perspectives of my object. What I want to do is a complete 360 degree rotation around the object with the camera. How is this possible? I already tried the components RandomLookAt and RandomMovement and RandomRotation, but it is not working.

**Comment by thangt** [comment]
You can use the orbital movement, you can find the details here: 
- https://github.com/NVlabs/Deep_Object_Pose/issues/59
- https://www.youtube.com/watch?v=2mU7I_q4OHg

**Comment by banannakn** [comment]
Thanks a lot!
