### ISSUE TITLE
Unable to find NVSceneCapturerGameMode_BP Game Mode

### ISSUE THREAD

**Issue by kevgeo** [NVIDIA/Dataset_Synthesizer#27]
Hi,
I am trying to create a simple synthetic cube/cuboid placed in an environment(level) and generate metadata which will give coordinates of the vertices of the cuboid. I am following the steps mentioned in the pdf which can be found on this [Ndds.pdf](https://github.com/NVIDIA/Dataset_Synthesizer/blob/master/Documentation/NDDS.pdf).

The problem is I'm unable to find the NVSceneCapturerGameMode_BP game logic through the UE4(Unreal Engine) but I can find it locally through the ubuntu file explorer. I've tried both the steps mentioned in last section of page 8 of the pdf but am unable to find it. The same problem with ScreenCapturer_Simple(mentioned on page 10 of pdf) which I can find through ubuntu file explorer but not through UE4.

Has anyone else faced the same problem? I'm not able to understand why UE4 can't recognise it.

**Comment by kevgeo** [comment]
I understood the error. The cloning of the repo is incomplete as the message "Downloading LFS objects: 0%" runs indefinitely and there is no progress in the download. Because of this, the file downloads are incomplete and shows NVSceneCapturerGameMode_BP and ScreenCapturer_Simple as txt files.

Now the issue is why the cloning of the repo stalls.
I used the command `git lfs clone https://github.com/NVIDIA/Dataset_Synthesizer.git` and my git lfs is installed properly.

**Comment by thangt** [comment]
I think the new version of git lfs doesn't require you to run `git lfs clone` but just `git clone` is enough. Which is your `git` and `git lfs` version? Also how long did you wait for `Downloading LFS objects: 0%`?

**Comment by kevgeo** [comment]
@thangt My `git --version` is 2.7.4 and `git-lfs --version` is 2.8.0.
Even after waiting overnight, it shows `Downloading LFS objects:   0% (0/1), 0 B | 0 B/s `.

With git clone, I'm getting the below smudge error.
```
Downloading` Documentation/NDDS.pdf (3.2 MB)
Error downloading object: Documentation/NDDS.pdf (25eb4ca): Smudge error: Error downloading Documentation/NDDS.pdf (25eb4cab49762b72f6fb6eff70775c4baea7892fac6a76b237ce35bcb578e2dd): batch response: Post https://github.com/NVIDIA/Dataset_Synthesizer.git/info/lfs/objects/batch: proxyconnect tcp: EOF
Errors logged to /home/ubuntu/Pictures/Dataset_Synthesizer/.git/lfs/logs/20191022T084446.270058838.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: Documentation/NDDS.pdf: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD' 
```

**Comment by thangt** [comment]
@kevgeo Your git version is a bit old, can you update it and try to `git clone` again?
Also do you get the smudge error with other files or just the documentation?

**Comment by kevgeo** [comment]
@thangt Sure, I will try updating my git and do git clone again. I get smudge error with the documentation and then it stops cloning.

**Comment by kevgeo** [comment]
@thangt I have solved the issue. The issue was mainly about the proxy network I was using. I just downloaded on a network with no proxy and it worked fine.

**Comment by thangt** [comment]
@kevgeo That's good too know. I didn't know git lfs have problem with proxy network like this.
