### ISSUE TITLE
How to export all falling sequences into the same folder

### ISSUE THREAD

**Issue by bjoern-braun** [NVIDIA/Dataset_Synthesizer#28]
Hey, 

I am currently creating my own dataset in the same way than the FAT dataset with help of the NDDS. For this purpose, I am using the Simple_Scene_Capturer, which has the options of overwriting, removing or creating a new directory with new timestamps to export pictures.

How did you export all pictures enumerated into one folder, when you were dropping the objects five times in the same location for the FAT dataset?
By creating a new directory with the timestamps, I would have to add all pictures together manually afterwards.

Thank you really much for your help!

Best regards,
Björn

**Comment by thangt** [comment]
@bjbraun `How did you export all pictures enumerated into one folder, when you were dropping the objects five times in the same location for the FAT dataset?` => for FAT, I used GroupActorManager (you can see it in the default map which use this class to spawn distractors) to spawn the training objects with SpawnDuration set to 5 seconds.
When SpawnDuration  set to a value > 0, it will spawn new set of object in a volume higher than the surface, wait for objects to fall down and respawn a new set.
The reason I don't have option in the SceneCapturer to add new captured files to an existing directory is we need to maintain the correct settings file: camera and objects, if the user change the camera settings then suddenly the old settings file are incorrect. Although it's doable, that settings will be quite error prone to the user.

**Comment by bjbraun** [comment]
Thank you really much, that was what I was looking for :).

However, I noticed that the objects sometimes do not get spawned inside the trigger volume but outside of it. Did you see this problem before?
