### ISSUE TITLE
Can't attach NVCapturableActorTag to Static Mesh (or Skeletal Mesh) Component of actor.

### ISSUE THREAD

**Issue by jmaierborst** [NVIDIA/Dataset_Synthesizer#30]
Hey, 

I am currently trying to get the bounding box of an item that a person is wearing. This person's skeleton is animated and has the item attached to its head (or hand, ...) with the help of a socket so that the item moves with the animation. My problem is that I can only attach the NVCapturableActorTag (which produces the bounding box) to the whole actor that is the person. But I am not able to attach the NVCapturableActorTag to a subpart of the skeletal mesh. When I try to move it there it tells me: "The selected component is not a scene component and cannot be attached to other components"
I have already tried to generate a moving actor that moves in a similar way like the person does and then place at the right location but this won't give me sufficiently good results.
Is there a solution or a better workaround for this problem? 
Thank you for your help!

![issue_NVCapturableActorTag](https://user-images.githubusercontent.com/54792227/68207907-4e183300-ffd0-11e9-8b0d-4b35e5434abf.PNG)

**Comment by thangt** [comment]
The current set up of the NVCapturableActorTag only tag the whole actor and not a child component. 
In your case, I'd create a new actor for the SK_Gloves and use ChildActorComponent to attach it to your physician.
https://github.com/NVlabs/Deep_Object_Pose/issues/58#issuecomment-515138626 => you can check my answer for a similar issue here.
https://www.youtube.com/watch?v=BFHf5HODpi8 => this is the video demonstrate the above issue

**Comment by jmaierborst** [comment]
Thank you for your quick reply @thangt. 
Sadly I wanna take into account the animation of the person walking and with a ChildActorComponent, for example like this:
![grafik](https://user-images.githubusercontent.com/54792227/68247735-b9d3bd80-001b-11ea-9132-b06d8c137324.png)
the actor won't follow the animation like in the pictures below
![000005](https://user-images.githubusercontent.com/54792227/68247218-9f4d1480-001a-11ea-814c-8c84920281c5.png)
![000000](https://user-images.githubusercontent.com/54792227/68247219-9f4d1480-001a-11ea-927d-2725647d0e22.png)
Because of that I thought using sockets is the right way to go...
Did I get your point right or do you thought of a different approach?

**Comment by thangt** [comment]
You should create a new blueprint for the physician. When you attach a ChildActorComponent to the skeletalMeshComponent, you can choose the ParentSocket that it should attach to.
You can check the example I have in the following image:
![image](https://user-images.githubusercontent.com/8795674/68252526-9f2d2480-ffda-11e9-9032-58bf67822dbb.png)

**Comment by jmaierborst** [comment]
Thank you for your response.
It worked out for me by creating a new blueprint with the added NVCapturableActorTag and the StaticMesh I wanted to track. Then I added this blueprint to the persons blueprint as a ChildActorComponent of the persons SkeletonMesh.
