### ISSUE TITLE
the object's location in json is wrong

### ISSUE THREAD

**Issue by kaixin-bai** [NVIDIA/Dataset_Synthesizer#36]
According to the tutorial video the object's location should in camera coordinate system like "location": [ 10.816499710083008, 39.035198211669922, 235]", but i got "location": [ 0, 0, 0 ]", and the visibility should be 0 according to the video, but i got 1. I'm confused, can somebody help me to find out what happens. Thanks a lot!

**Comment by thangt** [comment]
How did you setup the scene to capture?

**Comment by kaixin-bai** [comment]
just the same as in the tutorial video, i choose VR-Basic.

**Comment by kaixin-bai** [comment]
if i rebuild the whole environment, there's no such problem.
