### ISSUE TITLE
object collision with each other in TriggerVolume

### ISSUE THREAD

**Issue by kaixin-bai** [NVIDIA/Dataset_Synthesizer#38]
while generating dataset, the objects may have collision in Trigger Volume, how to fix this?
![Screenshot_2019-11-19_19-16-43](https://user-images.githubusercontent.com/38804949/69174320-d8e54b80-0b01-11ea-923c-cf9a9183d362.png)

**Comment by basedrhys** [comment]
![collision](https://user-images.githubusercontent.com/21359576/70764144-7b1fe880-1dbb-11ea-9fbd-c7f152bf13df.png)

Hi, having this issue too.

Thanks

**Comment by smitheric95** [comment]
In the blueprint editor for your actor, you can select how Unreal handles "spawn collisions". 

![Screenshot from 2019-12-13 08-57-08](https://user-images.githubusercontent.com/9437846/70809144-c966c480-1d86-11ea-9246-190b00b398d2.png)

**Comment by basedrhys** [comment]
Ah I figured out what I was doing wrong! 
I had the actor spawn collision handling set up correctly, however in the GroupActorManager, I had set the _minimum count per actor_ to the same as my max, which **forces** that number of actors to be spawned, even if they're colliding and you told them not to spawn when colliding. To anyone else, make sure you set your minimum count per actor low enough to stop this overriding behaviour (I just leave it at 1)

**Comment by basedrhys** [comment]
I've tried setting 'Do Not Spawn' on all my actors (GroupActorManager, TriggerVolume, Actor to spawn).

I've tried testing this out with a simple cube BP actor:
![CubeBP](https://user-images.githubusercontent.com/21359576/71032094-87b88e00-2179-11ea-9df2-9c68e7d0e7d2.png)

Here is my GroupActorManager and TriggerVolume
![GroupActorManager](https://user-images.githubusercontent.com/21359576/71032122-9737d700-2179-11ea-8764-0332f68e13a5.png)

![TriggerVolume](https://user-images.githubusercontent.com/21359576/71032131-9bfc8b00-2179-11ea-8c70-79a03bab8d30.png)

However when running this in game, the cubes still spawn and overlap (i purposely made them large and used a small trigger volume)

![OverlappingCubes](https://user-images.githubusercontent.com/21359576/71032184-b2a2e200-2179-11ea-829b-7affc825f91f.png)

One thing to note is that the cubes that are spawned have a different collision handling setting than was set in the CubeBP, it's almost as if that setting is being overwritten somewhere.

**Comment by kaixin-bai** [comment]
> In the blueprint editor for your actor, you can select how Unreal handles "spawn collisions".
> 
> ![Screenshot from 2019-12-13 08-57-08](https://user-images.githubusercontent.com/9437846/70809144-c966c480-1d86-11ea-9246-190b00b398d2.png)

i have tried, but it won't work while using TriggerVolume.

**Comment by wangjunfeng90214** [comment]
I also used the suggestion, but it didn't work

**Comment by wangjunfeng90214** [comment]
![000062](https://user-images.githubusercontent.com/20900567/77505876-513c8e80-6e9f-11ea-9d0b-b2926f5d73fb.png)
