### ISSUE TITLE
the object's center in json file is not correct.

### ISSUE THREAD

**Issue by kaixin-bai** [NVIDIA/Dataset_Synthesizer#39]
the output of the "location" in json file is not the center of the object's coordinate system.

![Screenshot_2019-11-22_16-30-56](https://user-images.githubusercontent.com/38804949/69438591-99a73c80-0d45-11ea-902e-1a946c61b023.png)
![Screenshot_2019-11-22_16-31-21](https://user-images.githubusercontent.com/38804949/69438596-9ad86980-0d45-11ea-97bd-56809d47649f.png)
![Screenshot_2019-11-22_16-31-44](https://user-images.githubusercontent.com/38804949/69438598-9c099680-0d45-11ea-8b38-e359899e01a0.png)

**Comment by kaixin-bai** [comment]
normally the "location" should be the center of the object's model, the "cuboid_centroid" should be the center of the 3D bounding box, if the object is not aligned, these two should not be the same. I find that in https://github.com/NVIDIA/Dataset_Synthesizer/issues/24 you mentioned that you have re-aligned the ycb models, what if i don't want to re-aligned the models' coordinate system. And i also find that in SIDOD dataset the "location" and "cuboid_centroid" are not same. Could you please tell me how to fix this? Thanks a lot!

000000.json
`"class": "YellowSaltCube_5k_tex",
                        "instance_id": 5,
                        "visibility": 1,
                        "location": [ 18.916999816894531, -9.5825004577636719, 55.503200531005859 ],
                        "quaternion_xyzw": [ -0.33019998669624329, 0.78210002183914185, -0.17749999463558197, -0.49779999256134033 ],
                        "pose_transform": [
                                [ -0.66149997711181641, -0.6062999963760376, -0.44130000472068787, 0 ],
                                [ -0.28630000352859497, -0.33970001339912415, 0.89590001106262207, 0 ],
                                [ 0.6930999755859375, -0.71899998188018799, -0.051100000739097595, 0 ],
                                [ 18.916999816894531, -9.5825004577636719, 55.503200531005859, 1 ]
                        ],
                        "cuboid_centroid": [ 18.916999816894531, -9.5825004577636719, 55.503200531005859 ],
                        "projected_cuboid_centroid": [ 444.0421142578125, 172.16169738769531 ]`

**Comment by juanmed** [comment]
@kaixin-bai Hi, how did you solve this?

**Comment by kaixin-bai** [comment]
> @kaixin-bai Hi, how did you solve this?

@juanmed I move the center of the objects to the center of the 3D bounding box, and convert the final output rotation from left- to right-handed coordinate system, then everything works fine.
