### ISSUE TITLE
do Dataset_Synthesizer support python API like blender  to generate dataset ?

### ISSUE THREAD

**Issue by v-wewei** [NVIDIA/Dataset_Synthesizer#42]

**Comment by thangt** [comment]
The current version doesn't support Python API yet. We do have plan to support it but I don't have a concrete estimate for it yet.

**Comment by v-wewei** [comment]
@thangt So, does NDDS support any program API for synghesize. Or any scipts for auto generation dataset e.g. Falling-things. Thanks, very much!
