### ISSUE TITLE
All training objects appear green. How do I change the color?

### ISSUE THREAD

**Issue by trevoravant** [NVIDIA/Dataset_Synthesizer#45]
This is probably an easy question, but I'm not an expert with Unreal and I've spent a bunch of time trying to figure this out.

I'm trying to create synthetic images for my own object. So I followed the **Creating a new Domain Randomization map** tutorial section of the NDDS Documentation pdf. Everything seemed to work fine, but my training object always renders as a green color. I can't figure out how to change the color.

**things I've tried:**
* opening `Content/Blueprint/TrainingObjects/Test_AnnotatedActor_BP` and changing *Static Mesh* to a different object
* changing the material of the training object
* playing with the *Light Source* and *Atmospheric Fog* settings
* re-doing the tutorial from the beginning

**Comment by trevoravant** [comment]
I just figured this out myself.

I went to the **Content Browser** and then to *Content > Blueprint > TrainingObjects* and double-clicked on *Test_AnnotatedActor_BP*. I got a note at the top that said 

<pre>
NOTE: This is a data only blueprint, so only the default values are shown.  It does not have any script or variables.  If you want to add some, <ins>Open Full Blueprint Editor</ins> 
</pre>

So I clicked the link to open the full blueprint editor, and went to **Components** and selected *Mesh Component*. Then, in **Details**, I went to *Materials*. That was where the green color was being set.

**Comment by fehimkus** [comment]
You saved my day sir :D
