### ISSUE TITLE
How do I get keypoints extraction?

### ISSUE THREAD

**Issue by darwinharianto** [NVIDIA/Dataset_Synthesizer#46]
Hello, thank you so much for this powerful tool!

If I am using a doll, is there any way I can extract every hinge location?
Position of neck, hands, legs, etc

https://github.com/NVIDIA/Dataset_Synthesizer/issues/46#tasklist-block-44aa0bbe-4719-4323-90de-c229cba56650

**Comment by kaixin-bai** [comment]
Since you already have the position of neck, hands, legs of the doll in object coordinate system, and you can also get the translation and rotation of the doll in camera coordinate system with NDDS, maybe you can just convert the coordinate system from object to camera, then you can get the position of keypoints in camera coordinate system.

**Comment by HaiyiMei** [comment]
@darwinharianto @kaixin-bai Hey guys, how did you solve this problem? I'm facing the same issues now. Thanks!

**Comment by darwinharianto** [comment]
@HaiyiMei Sorry for the late reply, I ended up making a cube and parented them inside object. Later on I used another script to convert them to COCO format.

**Comment by yangninghua** [comment]
> @HaiyiMei Sorry for the late reply, I ended up making a cube and parented them inside object. Later on I used another script to convert them to COCO format.

Excuse me, what does this mean? I don't quite understand it

**Comment by darwinharianto** [comment]
@yangninghua So instead of having one object, I created multiple objects. One object would be the main object, the others would be the 'keypoints'. Parenting other objects to main Objects would make them move together.
The resulting annotation would be Main object + other objects, and I just have to create a script that takes the other objects location as the keypoints. Hacky solution, but it works...
