### ISSUE TITLE
migrating assets to 4.22

### ISSUE THREAD

**Issue by marckernest** [NVIDIA/Dataset_Synthesizer#5]
hey folks, the assets in your 4.22 do not seem to be ready for that version. They are still formatted for 4.21. Any idea about how to fix this? My CAD imports do not have this issue.

**Comment by marckernest** [comment]
> hey folks, the assets in your 4.22 do not seem to be ready for that version. They are still formatted for 4.21. Any idea about how to fix this? My CAD imports do not have this issue.

seems that I just have to "migrate" individual assets and their dependencies....

**Comment by marckernest** [comment]
Maybe this is pedestrian, but the parent class won't properly migrate. So, I've lost my scene capturer completely... any advice?

**Comment by marckernest** [comment]
> Maybe this is pedestrian, but the parent class won't properly migrate. So, I've lost my scene capturer completely... any advice?

So I found a work-around, but now my datasmith importer has disappeared... in any other project, in any other version, it's still there. I tried uninstalling, and re-installing, but that did not help. Is this something you can help me with?

**Comment by marckernest** [comment]
Fixed it. When migrating assets, somehow the project is converted "out" of an unreal studio project. I went to EDIT > PLUGINS > UNREAL STUDIO > CONVERT. And that'll fix the issue. 

So to sum up:
No assets would appear when I opened a 4.21 NDDS project in 4.22. 

SOLUTION: Copy the original project folder and merge with the new project folder. Next, migrate all necessary assets from 4.21 to 4.22.

NOTE: Parent classes do not migrate automatically and must be done individually and then assigned to the asset.

This process seems to "convert out" of UNREAL STUDIO and disables DATASMITH.

SOLUTION: EDIT > PLUGINS > UNREAL STUDIO > CONVERT

**Comment by thangt** [comment]
```No assets would appear when I opened a 4.21 NDDS project in 4.22.``` => are you using the UnrealStudio or the normal Unreal editor? We didn't support or test with UnrealStudio so it's not guaranteed to work there.

**Comment by marckernest** [comment]
> No assets would appear when I opened a 4.21 NDDS project in 4.22. => are you using the UnrealStudio or the normal Unreal editor? We didn't support or test with UnrealStudio so it's not guaranteed to work there.

 "Unreal Studio" is just the name given for a set of tools and features offered in addition to the standard UE4.

**Comment by thangt** [comment]
```No assets would appear when I opened a 4.21 NDDS project in 4.22``` => do you mean you opened the NDDS version 1.1 in UE4 4.22? Our latest version 1.2 is converted to work with UE4 4.22 and I don't encounter any problems with the assets in the project.

**Comment by marckernest** [comment]
> No assets would appear when I opened a 4.21 NDDS project in 4.22 => do you mean you opened the NDDS version 1.1 in UE4 4.22? Our latest version 1.2 is converted to work with UE4 4.22 and I don't encounter any problems with the assets in the project.

this could be the case, but then I do not understand how to properly open the NDDS project I build in 4.21 in 4.22....
