### ISSUE TITLE
Failed to get "datas" in ".json" files of my "custom dataset" !?

### ISSUE THREAD

**Issue by avinashsen707** [NVIDIA/Dataset_Synthesizer#53]
when i compared with fat data set and my custom made data set i figured out following differences 
![fat file](https://user-images.githubusercontent.com/55526162/74232066-06e7bf80-4cee-11ea-9cfc-5b2d3df2711e.jpg)
![my dataset](https://user-images.githubusercontent.com/55526162/74232071-094a1980-4cee-11ea-8c7c-05a47dd12e16.jpg)

@swarren @aaronp24 @lukeyeager @drossetti @narendasan 
coud you please help in solving this problem! 

i encountered with following error in dope train.py code 
[(https://github.com/NVlabs/Deep_Object_Pose/issues/97#issuecomment-583229903)]

**Comment by avinashsen707** [comment]
solved by using object in test annotator plugin in the NDDS.

**Comment by KzZheng** [comment]
Your background looks great! Please, can you tell me where are you finding these levels if they are available?

**Comment by avinashsen707** [comment]
> Your background looks great! Please, can you tell me where are you finding these levels if they are available?

Actually my backgrounds are just .png images...
So there will be no segmentation in it...
So i prefer you to use...the backgrounds ue4 gives.

**Comment by chongyi-zheng** [comment]
@avinashsen707 Could you please tell me how to import images into UE4 and use it as dataset background?

**Comment by avinashsen707** [comment]
https://www.youtube.com/watch?v=qrhS-UxqNlQ

https://www.youtube.com/watch?v=bK2NJmRyP6g

Can you Go Through these videos.
