### ISSUE TITLE
Broken PDF and Window OS compatibility issue

### ISSUE THREAD

**Issue by yyc9268** [NVIDIA/Dataset_Synthesizer#58]
Nice augmentation library!
I am trying to utilize the synthesizer to augment my own pose-estimation dataset.
I have a few questions about this repository.
  Firstly, the guide PDF cannot be opened. It seems broken.
I want to confirm that it only happens to me or the file is really broken.
(https://github.com/NVIDIA/Dataset_Synthesizer/blob/master/Documentation/NDDS.pdf)

  Secondly, Is this library also available on Window OS?
Many examples and guidelines I found are all based on Linux OS.

Waiting for help from any pioneers :)

**Comment by patrickESM** [comment]
the .pdf file is not broken. it is just stored in a git lfs database.

you would have to clone the repository as described in the README.md file in order to get access to the file.

If you need help with that, feel free to comment below.

**Comment by yyc9268** [comment]
@patrickESM 
Thanks for comment. So, did you successfully opened the .pdf file? 
I think the git lfs database is not normally accessible now.

**Comment by patrickESM** [comment]
no i couldn't open it.

yeah the authors need to fix the lfs issue

**Comment by yyc9268** [comment]
I found the the alternative PDF file repository.
https://github.com/yehengchen/Synthetic-Data-UE4/blob/master/NDDS.pdf
But, it only includes PDF not the NDDS repository.
So, the git lfs problem should still be solved by the repository manager.

**Comment by thangt** [comment]
@yyc9268  I just posted an update and attach the compressed code there: https://github.com/NVIDIA/Dataset_Synthesizer/releases/download/1.2.2/ndds_1.2.2.zip.
Please try it out and let me know if you have any other troubles with it!
