### ISSUE TITLE
Object Visibilty 

### ISSUE THREAD

**Issue by m13ammed** [NVIDIA/Dataset_Synthesizer#59]
For some reason the visibility of static meshes is always zero in JSON file. commit : 71b759e didn't fix it for me, is there a special set up?

**Comment by IbrahimMCode** [comment]
> For some reason the visibility of static meshes is always zero in JSON file. commit : [71b759e](https://github.com/NVIDIA/Dataset_Synthesizer/commit/71b759e394a4a73f680b3371b82b7981102f6b3c) didn't fix it for me, is there a special set up?

Can you provide me with your email?

**Comment by m13ammed** [comment]
M.Rashed13@outlook.com

I really appreciate the help!
