### ISSUE TITLE
git lfs data limit reached

### ISSUE THREAD

**Issue by patrickESM** [NVIDIA/Dataset_Synthesizer#60]
The git lfs is currently broken. the data limit is reached is the error message. Same as the following issues #56 #58

**Comment by thangt** [comment]
@patrickESM Sorry for the trouble. I just posted an update and attach the compressed code there: https://github.com/NVIDIA/Dataset_Synthesizer/releases/download/1.2.2/ndds_1.2.2.zip.
Please try it out and let me know if you have any other troubles with it!

**Comment by patrickESM** [comment]
Thanks a lot @thangt . You saved us all a lot of trouble! I hope you find a new home for NDDS soon. Be it in Github, Gitlab or self hosted, as long as we get access to this amazing contribution for synthetic dataset generation! ;)
