### ISSUE TITLE
GPU Requirements

### ISSUE THREAD

**Issue by ShrutheeshIR** [NVIDIA/Dataset_Synthesizer#67]
Sorry, I have never used Unreal Engine before. Does this entire project require GPU, or can it be run on a CPU itself. If so, do I have to change anything? I plan to generate generate data for estimating 6DOF poses. 
Thanks!

**Comment by avinashsen707** [comment]
If you have gpu..the working will be better..
Or else you need better processing cpu.

I prefer use these softwares in workstations, to get better experience.
