### ISSUE TITLE
Build Instructions for Windows

### ISSUE THREAD

**Issue by ShrutheeshIR** [NVIDIA/Dataset_Synthesizer#68]
Hello!
I have a Windows 10 Machine. Since lfs is broken, I downloaded the zip file from one of the comments here. In the pdf, there are no build instructions for windows. It merely says run the .uproject file. I tried opening it with UE 4.22. It does not build successfully and says 'NDDS could not be compiled.Try rebuilding from source manually.' 

May be relevant info : I notice that there are two .sh files (though they seem to be linux specific)

Please let me know how to fix this issue

**Comment by ShrutheeshIR** [comment]
Hello. I solved the issue. Essentially UE4 installs Visual Studio 2017 tools by default, though I had VS 2019. I had to ensure that UE4 is linked to VS2019 first.

**Comment by tuhinmallick** [comment]
I am getting the same issue. How did you link the Visual Studio to the UE 4?
