### ISSUE TITLE
No access to LFS files

### ISSUE THREAD

**Issue by csingh27** [NVIDIA/Dataset_Synthesizer#70]
I get the following error when performing git lfs clone .....
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by SohaibAl-emara** [comment]
I am facing the same problem, any luck?

**Comment by thangt** [comment]
https://github.com/NVIDIA/Dataset_Synthesizer/releases/tag/1.2.2 => you can checkout this release and download the ndds_1.2.2.zip file.
Sorry for the trouble.

**Comment by csingh27** [comment]
Thanks @thangt
