### ISSUE TITLE
Random Textures don't work

### ISSUE THREAD

**Issue by KzZheng** [NVIDIA/Dataset_Synthesizer#73]
Hi, my unreal version is 4.22. And I add the RandomMaterialParam_Texture component into the actor. The parameter of material texture is show below. I input this parameter name into RandomMaterialParam_Texture, but it doesn't work.
![Selection_013](https://user-images.githubusercontent.com/62070113/81615874-62d6e880-93b0-11ea-9d90-51507e709860.png)

**Comment by smoothumut** [comment]
I also couldnt make it work, any advice? thanks in advance

**Comment by smoothumut** [comment]
> I also couldnt make it work, any advice? thanks in advance

Ok I have found it,, I have added texture Parameter in Material page, then rename the texture parameter as shown on the image above, and add that parameter name to the "Material Paramter Names" under randomMaterialParam_Texture tab
Thanks
