### ISSUE TITLE
Multiple Class IDs for a Single Object

### ISSUE THREAD

**Issue by akeaveny** [NVIDIA/Dataset_Synthesizer#75]
I wonder if it's possible to assign multiple class ids to a single object? I ask as I'm interested in Affordance Labelling. 

For the segmentation mask I am now looking for an easy way to generate data for an object like a hammer which has a label of 1 for the handle (grasp) and 2 for the head (pound). Similar to [this picture](https://people.eecs.berkeley.edu/~kanazawa/papers/affordanceRSSworkshop2014.pdf).

I've used ndds to train dope on a custom object so I am familiar with UE4. My thinking would be to have two different meshes.

Cheers!

![image](https://user-images.githubusercontent.com/56097508/82095371-e81e0e00-96cc-11ea-9a3d-69d35bb3a81b.png)

**Comment by kaixin-bai** [comment]
Hi, how did you solve this problem?
