### ISSUE TITLE
Class segmentation not work for object with translucent material

### ISSUE THREAD

**Issue by zhezhou1993** [NVIDIA/Dataset_Synthesizer#8]
I tried to export class segmentation image with scene has object with translucent material. It looks like the segmentation cannot gave any output of those objects.  I think it may caused by translucent material doesn't write to depth buffer and it won't work with depth grabber and segmentation? If it is true, anyone has any workaround idea?

**Comment by zhezhou1993** [comment]
Just find a solution for that:
1. Check Allow Custom Depth writes for the material
2. Change Opacity Mask Clip Value to 0 for the material instance

**Comment by bmunkhtulga** [comment]
Thanks for solution. I got it working with class segmentation. But did you make it work with depth image? In my case, in the depth image there is nothing. 

This is class segmentation.
![000000 cs](https://user-images.githubusercontent.com/45383657/63909389-75490600-ca5d-11e9-9fd7-b1cc072eec24.png)

And below is depth image. 
![000000 depth](https://user-images.githubusercontent.com/45383657/63909391-75490600-ca5d-11e9-9fea-03c2ce994056.png)

![000000](https://user-images.githubusercontent.com/45383657/63909458-a7f2fe80-ca5d-11e9-8771-409c79a020ae.png)
