### ISSUE TITLE
question about annotations

### ISSUE THREAD

**Issue by KatharinaSchmidt** [NVIDIA/Dataset_Synthesizer#84]
I created a synthetic dataset including annotations in a .json-file with your repo, that worked fine. 
Now I try to train [PVNet](https://github.com/zju3dv/clean-pvnet) with this dataset. I already customized the clean-pvnet-code. So I am able to load the images and start training. But when I visualize my test-results, I can see that the ground-truth-pose is loaded wrong. 
I know that the annotated pose is correct (I checked it with [NVDU](https://github.com/NVIDIA/Dataset_Utilities)). 
So I think that I took the wrong pose-annotation from the .json-file. 
In fact I need the pose of my object relative to the camera including translation t and rotation R. 
It shall look like this: 
```
[a, b, c, d]
[e, f, g, h]
[i, j, k, l]
```
with rotation:
```
[a, b, c]
[e, f, g]
[i, j, k]
```
and translation:
```
[d, h, l]
```

I used the matrix inside of "pose_transform" (that's a 4x4 matrix), deleted the last column (so it's a 3x4 matrix) and transposed it. In the end I get a 4x3 matrix. But it seems to be wrong. 
Can you help me and explain to me which annotation I have to use for the 6D-pose in relation to camera?

**Comment by KatharinaSchmidt** [comment]
I made some progress with reading the pose annotations correctly. But my Bounding Box still doesn't match: 
![Bildschirmfoto von 2020-08-05 15-03-09](https://user-images.githubusercontent.com/62353042/89424205-c9fa0400-d737-11ea-80f2-da21115b5474.png)
![Bildschirmfoto von 2020-08-05 15-03-26](https://user-images.githubusercontent.com/62353042/89424237-d1b9a880-d737-11ea-956e-1733b06e3489.png)

That's my code for reading: 
``` ruby
with open(pose_path,'r') as file:
            annotation = json.loads(file.read())
        
        objekt = annotation['objects']
        objekt_klasse = objekt[0]["class"]

        if klasse in objekt_klasse:

            translation = np.array(objekt[0]['location']) * 10

            quaternion_obj2cam = R.from_quat(np.array(objekt[0]['quaternion_xyzw']))
            mirrored_y_axis = np.dot(quaternion_obj2cam.as_matrix(), np.array([[-1, 0, 0], [0, -1, 0], [0, 0, 1]]))
            mirrored_y_axis = np.dot(mirrored_y_axis, np.array([[0, 1, 0], [-1, 0, 0], [0, 0, 1]]))

            pose = np.column_stack((mirrored_y_axis, translation))

            corner_2d = np.array(objekt[0]['projected_cuboid'])
            center_2d = np.array(objekt[0]['projected_cuboid_centroid'])
            print(pose)
```
I multiply the location with 10, because I need the position in meter. But even if I take the values for the green BoundingBox directly from the .json-file (corner_2d) like in the pictures above, the drawn boxes are still wrong.

Maybe someone can help me and give me some advice?

**Comment by ctxqlxs** [comment]
help..how to solve it ?^_^ @KatharinaSchmidt

**Comment by kaixin-bai** [comment]
ue4 exports the poses under the left-handed coordinate system, try to convert it to right-handed before you do 6d pose estimation task.
