### ISSUE TITLE
How can I use Datasmith for NDDS?

### ISSUE THREAD

**Issue by dedoogong** [NVIDIA/Dataset_Synthesizer#88]
To import 3d max designed in 3d max, I need to use datasmith plug-in for Unreal Engine. 
I can import the 3d model with material/texture setup in the normal arch viz project in unreal editor. 
but I can't do it only in NDDS project. 

Please give me any hint how to solve this. 

Thank you very much!

**Comment by SanggunLee** [comment]
datasmith is unreal 4.23 부터 지원되는 거라서 안될겁니다.
4.23 이상 Unreal engine 에서 NDDS 실행해보세요
