### ISSUE TITLE
Object visibility

### ISSUE THREAD

**Issue by bmunkhtulga** [NVIDIA/Dataset_Synthesizer#9]
Hey guys, thanks for making this public. I was wondering about visibility in meta data (for example: 0000.json file). In [this video ](https://github.com/NVIDIA/Dataset_Synthesizer/blob/master/Videos/data_overview.mp4), you guys explained that visibility = 0 is fully visible, and 1 is completely occluded. But in FAT dataset, it is kinda opposite. 

![image](https://user-images.githubusercontent.com/45383657/62829208-c1114800-bc33-11e9-87e1-122e180952cf.png)

Which one is right? All the data I am exporting have visibility set to 0. How can I change this value?

**Comment by thangt** [comment]
`visibility=0` mean fully occluded, `visibility=1` mean full visible.
I just check the code again and I found there is a problem with the way the capturer actor set up which cause its collision area to block the visibility check and cause all the visibility check to fail (all 0).
Thanks for reporting this problem, I will add the fix for this issue in the future release!

**Comment by thangt** [comment]
@bmunkhtulga In the latest commits make sure the camera's mesh will ignore the visibility check thus it will not occlude objects anymore. Can you pull the latest commits and check it out?

**Comment by bmunkhtulga** [comment]
Thank you for response and quick commit. I have tried it. So in other words, visibility is going to be constant 1, no matter what?

**Comment by thangt** [comment]
It shouldn't always be 1. It should be: ```visibility=0 mean fully occluded, visibility=1 mean full visible.```
I tested again and I found that my visibility ratio detection work fine with objects which have its collision setup, but if the object doesn't have collision setup then it's wrong.

I have a fix for this internally, I will let you know when we publish it.

**Comment by bmunkhtulga** [comment]
All right. Thank you very much.

**Comment by thangt** [comment]
@bmunkhtulga The bug is fixed in the latest commit: https://github.com/NVIDIA/Dataset_Synthesizer/commit/71b759e394a4a73f680b3371b82b7981102f6b3c.
Please pull and check it out!
